name: GT-Pro
channels:
  - bioconda
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - biopython=1.81=py39hd1e30aa_1
  - blas=1.0=mkl
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.11.26=h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - kmc=3.2.1=hf1761c0_2
  - lbzip2=2.5=0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgomp=14.2.0=h77fa898_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libzlib=1.2.13=h4ab18f5_6
  - lz4=4.3.2=py39h5eee18b_0
  - lz4-c=1.9.4=h6a678d5_1
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py39h5eee18b_1
  - mkl_fft=1.3.11=py39h5eee18b_0
  - mkl_random=1.2.8=py39h1128e8f_0
  - ncurses=6.4=h6a678d5_0
  - numpy=1.24.3=py39hf6e8229_1
  - numpy-base=1.24.3=py39h060ed82_1
  - openssl=3.0.15=h5eee18b_0
  - pigz=2.6=h27cfd23_0
  - pip=24.2=py39h06a4308_0
  - python=3.9.21=he870216_1
  - python_abi=3.9=2_cp39
  - readline=8.2=h5eee18b_0
  - setuptools=75.1.0=py39h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - tzdata=2024b=h04d1e81_0
  - wheel=0.44.0=py39h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h4ab18f5_6
