name: kneaddata-latest
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blast=2.12.0=pl5262h3289130_0
  - bmtool=3.101=he1b5a44_3
  - bowtie2=2.4.4=py37h13ad519_0
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.7.2=h06a4308_0
  - certifi=2022.12.7=py37h06a4308_0
  - curl=7.88.1=h37d81fd_2
  - dbus=1.10.20=0
  - entrez-direct=22.4=he881be0_0
  - expat=2.1.0=0
  - fastqc=0.12.1=hdfd78af_0
  - font-ttf-dejavu-sans-mono=2.37=0
  - fontconfig=2.12.1=3
  - freetype=2.5.5=2
  - glib=2.69.1=he621ea3_2
  - kneaddata=0.12.0=pyhdfd78af_1
  - krb5=1.20.1=h568e23c_1
  - ld_impl_linux-64=2.38=h1181459_1
  - libcurl=7.88.1=h91b91d3_2
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.14=0
  - libidn2=2.3.4=h5eee18b_0
  - libnghttp2=1.52.0=ha637b67_1
  - libpng=1.6.30=1
  - libssh2=1.10.0=h37d81fd_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libunistring=0.9.10=h27cfd23_0
  - libxcb=1.12=1
  - libxml2=2.9.4=0
  - lz4-c=1.9.4=h6a678d5_1
  - ncurses=6.4=h6a678d5_0
  - openjdk=11.0.13=h87a67e3_0
  - openssl=1.1.1w=h7f8727e_0
  - pcre=8.45=h295c915_0
  - perl=5.26.2=h14c3975_0
  - perl-archive-tar=2.32=pl526_0
  - perl-carp=1.38=pl526_3
  - perl-common-sense=3.74=pl526_2
  - perl-compress-raw-bzip2=2.087=pl526he1b5a44_0
  - perl-compress-raw-zlib=2.087=pl526hc9558a2_0
  - perl-exporter=5.72=pl526_1
  - perl-exporter-tiny=1.002001=pl526_0
  - perl-extutils-makemaker=7.36=pl526_1
  - perl-io-compress=2.087=pl526he1b5a44_0
  - perl-io-zlib=1.10=pl526_2
  - perl-json=4.02=pl526_0
  - perl-json-xs=2.34=pl526h6bb024c_3
  - perl-list-moreutils=0.428=pl526_1
  - perl-list-moreutils-xs=0.428=pl526_0
  - perl-pathtools=3.75=pl526h14c3975_1
  - perl-scalar-list-utils=1.52=pl526h516909a_0
  - perl-types-serialiser=1.0=pl526_2
  - perl-xsloader=0.24=pl526_0
  - pip=22.3.1=py37h06a4308_0
  - python=3.7.16=h7a1cb2a_0
  - python_abi=3.7=2_cp37m
  - readline=8.2=h5eee18b_0
  - samtools=1.5=1
  - setuptools=65.6.3=py37h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - srprism=2.4.24=h96824bc_3
  - tbb=2020.3=hfd86e86_0
  - tk=8.6.14=h39e8969_0
  - trf=4.09.1=hec16e2b_2
  - trimmomatic=0.39=hdfd78af_2
  - wget=1.21.4=h91b91d3_1
  - wheel=0.38.4=py37h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.4.9=haebb681_0
prefix: /home/data/CYM/mambaforge/envs/kneaddata-latest
