name: quickvariants
channels:
  - caozhichongchong
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - bioconda
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _sysroot_linux-64_curr_repodata_hack=3=haa98f57_10
  - alsa-lib=1.2.13=hb9d3cd8_0
  - bcftools=1.21=h8b25389_0
  - bowtie2=2.5.4=he96a11b_5
  - bwa=0.7.18=h577a1d6_2
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.3=hb9d3cd8_1
  - ca-certificates=2024.11.26=h06a4308_0
  - cairo=1.18.2=h3394656_1
  - font-ttf-dejavu-sans-mono=2.37=0
  - font-ttf-inconsolata=2.000=0
  - font-ttf-source-code-pro=2.030=0
  - font-ttf-ubuntu=0.83=0
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - freetype=2.12.1=h267a509_2
  - gdbm=1.18=hd4cb3f1_4
  - giflib=5.2.2=h5eee18b_0
  - graphite2=1.3.14=h295c915_1
  - gsl=2.7.1=h6e86dc7_1
  - harfbuzz=10.1.0=h0b3b770_0
  - htslib=1.21=h5efdd21_0
  - icu=75.1=he02047a_0
  - k8=1.2=h6618dc6_3
  - kernel-headers_linux-64=3.10.0=h57e8cba_10
  - krb5=1.21.3=h143b758_0
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h27087fc_0
  - libblas=3.9.0=25_linux64_openblas
  - libcblas=3.9.0=25_linux64_openblas
  - libcups=2.3.3=h4637d8d_4
  - libcurl=8.10.1=hbbe4b11_0
  - libdeflate=1.21=h4bc722e_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libexpat=2.6.4=h5888daf_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgfortran=14.2.0=h69a702a_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libglib=2.82.2=h2ff4ddf_0
  - libgomp=14.2.0=h77fa898_1
  - libiconv=1.17=hd590300_2
  - libjpeg-turbo=3.0.3=h5eee18b_0
  - liblapack=3.9.0=25_linux64_openblas
  - liblzma=5.6.3=hb9d3cd8_1
  - libnghttp2=1.64.0=h161d5f1_0
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.28=pthreads_h94d23a6_1
  - libpng=1.6.44=hadc24fc_0
  - libsqlite=3.47.2=hee588c1_0
  - libssh2=1.11.1=hf672d98_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libtiff=4.7.0=h6565414_0
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - minimap2=2.28=he4a0461_3
  - ncurses=6.5=he02047a_1
  - numpy=2.2.0=py312h7e784f5_0
  - openjdk=23.0.1=h68779a4_1
  - openssl=3.4.0=hb9d3cd8_0
  - pandas=2.2.3=py312hf9745cd_1
  - pcre2=10.44=hba22ea6_2
  - perl=5.34.0=h5eee18b_2
  - pip=24.2=py312h06a4308_0
  - pixman=0.44.2=h29eaf8c_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.12.8=h9e4cc4f_1_cpython
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.12=5_cp312
  - pytz=2021.3=pyhd3eb1b0_0
  - quick-variants=1.1.0=0
  - readline=8.2=h5eee18b_0
  - samtools=1.21=h50ea8bc_0
  - setuptools=75.1.0=py312h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sysroot_linux-64=2.17=h57e8cba_10
  - tk=8.6.13=noxft_h4845f30_101
  - tzdata=2024b=h04d1e81_0
  - wheel=0.44.0=py312h06a4308_0
  - xorg-libice=1.1.1=hb9d3cd8_1
  - xorg-libsm=1.2.4=he73a12e_1
  - xorg-libx11=1.8.10=h4f16b4b_1
  - xorg-libxau=1.0.11=hb9d3cd8_1
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.11=hb9d3cd8_2
  - xorg-libxt=1.3.1=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xz=5.4.6=h5eee18b_1
  - zstd=1.5.6=ha6fb4c9_0
