name: SGVFinder2
channels:
  - https://mirrors.ustc.edu.cn/anaconda/cloud/bioconda
  - https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/main
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/free
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - blas=1.0=openblas
  - bokeh=3.2.2=pyhd8ed1ab_0
  - bowtie2=2.5.4=h7071971_4
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.9.24=h06a4308_0
  - contourpy=1.2.0=py310hdb19cb5_0
  - cython=3.0.2=py310hc6cd4ac_2
  - freetype=2.12.1=h267a509_2
  - gdbm=1.18=hd4cb3f1_4
  - htslib=1.21=h5efdd21_0
  - jinja2=3.1.4=py310h06a4308_1
  - krb5=1.20.1=h143b758_1
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.43=h712a8e2_2
  - lerc=4.0.0=h27087fc_0
  - libblas=3.9.0=16_linux64_openblas
  - libcblas=3.9.0=16_linux64_openblas
  - libcurl=8.9.1=h251f7ec_0
  - libdeflate=1.20=hd590300_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgfortran-ng=8.2.0=hdf63c60_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libgomp=14.2.0=h77fa898_1
  - libjpeg-turbo=3.0.3=h5eee18b_0
  - liblapack=3.9.0=16_linux64_openblas
  - libnghttp2=1.57.0=h2d74bed_0
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.21=h043d6bf_0
  - libpng=1.6.39=h5eee18b_0
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.11.0=h251f7ec_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libtiff=4.6.0=h1dd3fc0_3
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.15=h7f8727e_0
  - libzlib=1.2.13=h4ab18f5_6
  - markupsafe=2.1.3=py310h5eee18b_0
  - ncurses=6.5=he02047a_1
  - numpy=1.26.0=py310heeff2f4_0
  - numpy-base=1.26.0=py310h8a23956_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.4.0=hb9d3cd8_0
  - packaging=24.1=py310h06a4308_0
  - pandas=2.1.0=py310hcc13569_0
  - perl=5.34.0=h5eee18b_2
  - pillow=10.3.0=py310hf73ecf8_0
  - pip=24.3.1=pyh8b19718_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pysam=0.21.0=py310h41dec4a_1
  - python=3.10.12=hd12c33a_0_cpython
  - python-dateutil=2.9.0post0=py310h06a4308_2
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.10=5_cp310
  - pytz=2024.1=py310h06a4308_0
  - pyyaml=6.0.2=py310h5eee18b_0
  - readline=8.2=h8228510_1
  - samtools=1.21=h50ea8bc_0
  - scipy=1.11.2=py310hb13e2d6_1
  - setuptools=75.3.0=pyhd8ed1ab_0
  - six=1.16.0=pyhd3eb1b0_1
  - tk=8.6.13=noxft_h4845f30_101
  - tornado=6.4.1=py310h5eee18b_0
  - tzdata=2024b=hc8b5060_0
  - ujson=5.8.0=py310hc6cd4ac_0
  - wheel=0.45.0=pyhd8ed1ab_0
  - xorg-libxau=1.0.11=hb9d3cd8_1
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xyzservices=2022.9.0=py310h06a4308_1
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h4ab18f5_6
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - bio==1.7.1
      - biopython==1.84
      - biothings-client==0.3.1
      - certifi==2024.8.30
      - charset-normalizer==3.4.0
      - gprofiler-official==1.0.0
      - idna==3.10
      - mygene==3.2.2
      - platformdirs==4.3.6
      - pooch==1.8.2
      - requests==2.32.3
      - sgvfinder2==0.0.1
      - tqdm==4.67.0
      - urllib3==2.2.3
